### ISSUE TITLE
Error with  prevent-riptide from cheat-prevention addon

### ISSUE THREAD

**Issue by SrBedrock** [SirBlobman/CombatLogX#123]
**Describe the bug**

When prevent-riptide: true in the settings of the cheat-prevention addon, even if you are not in combat you cannot use.

```yml
items:
  # Set this to true if the riptide enchantment effect should be cancelled during combat
  # Set this to false to allow the riptide enchantment effect
  # This option will be ignored on versions where the riptide enchantment does not exist.
  #
  # Default: true
  prevent-riptide: true
```
**To Reproduce**

1. Set the option prevent-riptide to true;
2. Use the `/weather rain` command; 
3. Try to use the riptale enchantment without being in combat.

**Expected behavior**

Being able to use the enchantment normally when not in combat.

**Screenshots**

![image](https://user-images.githubusercontent.com/51332006/84587166-408f1b00-adf3-11ea-8035-98e6897d35a9.png)

**Minecraft and CombatLogX Version**

![image](https://user-images.githubusercontent.com/51332006/84587153-2bb28780-adf3-11ea-83a8-24c12da3b450.png)
