### ISSUE TITLE
Re-enable flight requires permission to work

### ISSUE THREAD

**Issue by gabrielsilvavieira** [SirBlobman/CombatLogX#370]
### Server Implementation

Paper

### Server Version

1.8.9

### CombatLogX Version

**Latest version:**

![download](https://user-images.githubusercontent.com/62969752/155920384-a72cc86b-aecc-4bc8-97d5-959dcd958c8d.png)

### Feature Request

Permission to reactivate player's fly when combat is over

![Screenshot_3](https://user-images.githubusercontent.com/62969752/155920862-47d1589e-0d2b-462a-8ee6-b1dfe05a84b7.png)

**Comment by SirBlobman** [comment]
V11 does not use re-enable flight, it handles this differently. Sorry for any inconvenience.

Cheat Prevention `flight.yml` in V11:
```yml
# Should players be prevented from flying during combat?
# Default: true
prevent-flying: true

# If a players flight is deactivated by CombatLogX, should the plugin prevent them from taking fall damage?
# The fall damage prevention only works once after flight is disabled.
# Default: true
prevent-fall-damage: true

# Should the 'allow-flight' flag be set to false on a player?
# This may prevent toggle spam but players won't be able to fly after combat ends.
# Default: false
force-disable-flight: false

```
